---

- name: Install Python 2 if not exist
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  when: ansible_os_family == 'Debian'


- name: Upgrade system packages on Debian/Ubuntu
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian'


- name : Add WireGuard repository to Debian
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    state: present
    filename: unstable-wireguard.list
    update_cache: yes
  when: ansible_distribution == 'Debian'


- name: Configure APT to use unstable Debian repository with low priority
  copy:
    src: limit-unstable
    dest: /etc/apt/preferences.d/limit-unstable
  when: ansible_distribution == 'Debian'


- name: Install kernel headers on Debian/Ubuntu
  shell: apt install -y linux-headers-`uname -r`
  when: ansible_os_family == 'Debian'


# vim: set ft=ansible ts=2 sw=2 tw=0 et :
